Merge changes from Gosha-iv
MasterZydra/WurzelimperiumBot pull request #19
Opened 2022-06-30 15:34 UTC by MasterZydra

2022-07-01 06:33 UTC, MrFlamez commented
> @MrFlamez @xRuffKez Was denkt ihr? Eine Frage die beim Quellcode anschauen auftaucht ist, welche Sprache wir im Quellcode nehmen wollen. Deutsch oder Englisch.

Grundsätzlich stört mich die Mischung und Standard wäre für mich auch Englisch. Bei diesem Projekt bin ich mir allerdings nicht sicher, weil das Browserspiel regional schon sehr begrenzt ist. Ich glaube kaum, dass es hier internationale Spieler gibt. Falls doch wird der Anteil (vernachlässigbar?) gering sein. Daher finde ich deutsch in diesem Fall sogar angemessener.

2022-07-01 06:33 UTC, MrFlamez submitted a review, later dismissed

2022-07-01 06:40 UTC, MrFlamez commented on src/Garten.py
> +    def clearWeedField(self, field_id):
Es gibt bereits die Methode removeWeed in der Garten-Klasse

2022-07-01 07:13 UTC, xRuffKez requested changes
Is your repo up to date? Main.py got changed to Logger.py and the def in it

2022-07-01 07:16 UTC, xRuffKez approved these changes

2022-07-01 07:19 UTC, xRuffKez requested changes
Your repo is not up to date

2022-07-01 15:06 UTC, xRuffKez commented
Ich würde es auch auf deutsch belassen, maximal englisch. Der Anteil an nicht deutsche Spieler ist verschwindend gering und die Chance, dass diese noch den Bot nutzen so gut wie nicht existent.

2022-07-01 16:16 UTC, xRuffKez commented
Merged

2022-07-01 19:37 UTC, MrFlamez commented
Ich bin der Meinung, dass ein Merge zu früh war. Ich habe den Pull Request aus Versehen zu früh approved. Ich dachte das wäre nur für eine Datei die man abhaken kann, sry.

Der Grund:
Es gibt mit diesem PR eine Methode der Garten-Klasse clearWeedField. Die wurde bereits von mir implementiert unter anderem Namen (removeWeed). Des Weiteren habe ich damals auch die Wurzelbot-Klasse erweitert und auch das automated_script wurde angepasst. Mit diesem Merge ist meine Methode verschwunden und hat somit zu Inkonsistenzen geführt. Äußerst unschön.

Noch dazu konnte ich mir noch nicht alle Stellen ansehen.

2022-07-01 19:52 UTC, MasterZydra commented
@MrFlamez
Meine Änderungen sind auch teilweise rausgeflogen.
Das Problem ist ja jetzt, dass der Merge schon durch ist. Wir sollten über den Merge-Commit nochmal drüberschauen und entsprechende Stellen wieder reinnehmen.

2022-07-01 20:27 UTC, Pazze12 commented
Können wir den merge commit nicht einfach reverten?

On Fri, 1 Jul 2022, 22:53 David Hein, ***@***.***> wrote:

> @MrFlamez <https://github.com/MrFlamez>
> Meine Änderungen sind auch teilweise rausgeflogen.
> Das Problem ist ja jetzt, dass der Merge schon durch ist. Wir sollten über
> den Merge-Commit nochmal drüberschauen und entsprechende Stellen wieder
> reinnehmen.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MasterZydra/WurzelimperiumBot/pull/19#issuecomment-1172669105>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALO5BIEDXAUXDHDEVBQ4X7TVR5ECBANCNFSM52JZKN2A>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-07-01 21:01 UTC, MasterZydra commented
@Pazze12 Prinzipiell ja. Da müssen wir dann genau schauen, was von den darauf folgenden Commits auch rückgängig gemacht wird. 
Der einfachste aber auch unschönste Weg wäre alles auf den Commit vor dem Merge zurückzurollende.

2022-07-03 12:54 UTC, Gosha-iv commented
> Ich würde es auch auf deutsch belassen, maximal englisch. Der Anteil an nicht deutsche Spieler ist verschwindend gering und die Chance, dass diese noch den Bot nutzen so gut wie nicht existent.
> 
> Man könnte dennoch eine lang csv nutzen und Variablen als Englisch definieren und die strings standardmäßig auf deutsch machen, wer bock drauf hat kann diese sich gerne übersetzen

Do you really think that the game is distributed only on German servers. Servers for the game exist in 16 languages. And I play at least 3 languages. (English, Russian, German). And believe me, I'm not playing alone. For example, I will give a link to the bot project of another game from upjers: https://github.com/HackerHarry/mffbashbot

2022-07-04 05:38 UTC, MasterZydra commented
@Gosha-iv @MrFlamez 
How about checking the amount of users the other languages have?
We could get an approximation by looking at the amount of servers per language.

2022-07-04 05:51 UTC, MasterZydra commented
https://www.wurzelimperium.de/   46
https://www.zieloneimperium.pl/ 21
https://www.kertbirodalom.hu/ 5
https://www.sadowajaimperija.ru/ 5
https://www.bahcivanlardiyari.com/ 5
https://www.zeleneimperium.cz/ 4
https://www.molehillempire.com/ 4
https://www.molehillempire.es/ 3
https://www.molehillempire.fr/ 3
https://www.bg.molehillempire.com/ 2
https://www.molehillempire.nl/ 2
https://www.molehillempire.ro/ 2
https://www.molehillempire.se/ 2

Sum of all servers = 104
Sum of all servers - DE = 58

DE = 44% of Servers

2022-07-04 05:54 UTC, MasterZydra commented
So based on the numbers our bot could be used by a lot more people if we would provide it in e. g. English.
The library https://github.com/danhper/python-i18n for example could be used so that we can make it easy to add more languages.

2022-07-04 12:23 UTC, MrFlamez commented
> @Pazze12 Prinzipiell ja. Da müssen wir dann genau schauen, was von den darauf folgenden Commits auch rückgängig gemacht wird. Der einfachste aber auch unschönste Weg wäre alles auf den Commit vor dem Merge zurückzurollende.

Mit "git revert HEAD~0" kann man den letzten Commit rückgängig machen. Danach gab es doch keine mehr oder? Anstelle der 0 kann man auch einen anderen Commit wählen.

2022-07-04 12:27 UTC, MrFlamez commented
> @Gosha-iv @MrFlamez How about checking the amount of users the other languages have? We could get an approximation by looking at the amount of servers per language.
> 
> That way we can make the decision based on numbers instead of guesses.

i didnt know, that there are servers in other languages, thx. with this information i would suggest to use a language csv file. (suggestion from @xRuffKez ). we still need people who can translage the docstrings. the main language of the src code should be english.

2022-07-04 14:35 UTC, MasterZydra commented
@MrFlamez Today @xRuffKez already started by adding i18n. So we just have to change the output or return of strings with the translation function and add the translations into the lang folder.

2022-07-05 17:55 UTC, MasterZydra commented on .gitignore
> +# Some local files
The `.idea` folder is a good addition.
I am unsure about the local files. I would prefer to not include some "random" filenames.
@MrFlamez @xRuffKez What is your opinion?

2022-07-09 22:19 UTC, xRuffKez commented
Please open a new Pull request on changes and new features.

2022-07-09 22:19 UTC, closed without merging